START_WINDOW_NAME = 'start_window'
MAIN_MENU_WINDOW_NAME = 'main_menu_window'
LEVELS_LIST_WINDOW_NAME = 'level_list_window'
LEVEL_WINDOW_NAME = 'level_window'
PROFILE_ACTIONS_MENU_WINDOW_NAME = 'profile_actions_menu_window'
PROFILES_MENU_WINDOW_NAME = 'profiles_menu_window'
RESTART_WINDOW_NAME = 'restart_window'
STATISTICS_WINDOW_NAME = 'statistics_window'
