PROFILES_LAYOUT_POS = 0.05, 0.05
PROFILES_LAYOUT_SIZE = 0.6, 0.9
PROFILES_LAYOUT_SPACING = 0.03
PROFILES_LAYOUT_NAME = 'profiles_layout_name'

PROFILE_IMAGE_PATH = 'data/images/windows/profiles_menu_window/profile.jpg'

RADIO_BUTTON_SELECTION_LINE_WIDTH = 0.01