from constants.gui.colors import RED, GREEN

CLOSED_ICON_COLOR = RED
OPENED_ICON_COLOR = GREEN

LEVELS_LAYOUT_FONT_SIZE = 0.1
LEVELS_LAYOUT_ORDER_POS = 10, 10
LEVELS_LAYOUT_SPACING = 0.02
LEVELS_LAYOUT_SIZE = 0.8, 0.8
LEVELS_LAYOUT_POS = 0.1, 0.1
LEVELS_LAYOUT_NAME = 'levels_layout_name'

LEVEL_ICON_NAME = 'level_icon'
LEVEL_ICON_MIN_SIZE = 0.1, 0.15
