from constants.windows.windows_names import LEVEL_EDITOR_WINDOW_NAME
from constants.main_settings import SIZE
from constants.gui.colors import CUSTOM_BLUE, CUSTOM_GREEN, CUSTOM_RED, WHITE

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500
LEVEL_EDITOR_WINDOW_NAME = LEVEL_EDITOR_WINDOW_NAME
TITLE = "Level Editor"
LOWER_MARGIN = 100
SIDE_MARGIN = 300
ROWS = 16
MAX_COLS = 100
TILE_SIZE = SIZE.HEIGHT // ROWS
TILE_TYPES = 14
GREEN = CUSTOM_GREEN
RED = CUSTOM_RED
BLUE = CUSTOM_BLUE
WHITE = WHITE
